openstack_user:
    resource: "@OpenStackUserBundle/Resources/config/routing.yml"
    prefix:   /

openstack_commande:
    resource: "@OpenStackcommandeBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:     /login
    defaults: { _controller: OpenStackUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

## Registration with FOSUserBundle ##
#openstack_inscription:
#    pattern:    /inscription/
#    defaults:    { _controller: OpenStackUserBundle:Registration:registerForm }

## Registration without FOSUserBundle ##
openstack_inscription:
    pattern:    /inscription/
    defaults:   { _controller: OpenStackUserBundle:Registration:register }
    
openstack_profil_show:
    pattern:    /profil/
    defaults:   { _controller: OpenStackUserBundle:Profile:show }
    
openstack_profil_edit:
    pattern:    /profil/editer
    defaults:   { _controller: OpenStackUserBundle:Profile:edit }